-- GENERATED by scripts/emit-schema.ts from server/store.ts — do not edit.
-- Regenerate with: bun run db:schema

CREATE TABLE IF NOT EXISTS users (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    name       TEXT NOT NULL,
    name_lower TEXT NOT NULL UNIQUE,
    pass       TEXT NOT NULL,
    created_at INTEGER NOT NULL
  );
CREATE TABLE IF NOT EXISTS sessions (
    token      TEXT PRIMARY KEY,
    user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at INTEGER NOT NULL,
    expires_at INTEGER NOT NULL
  );
CREATE INDEX IF NOT EXISTS sessions_user ON sessions(user_id);
CREATE TABLE IF NOT EXISTS solves (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    puzzle_key TEXT NOT NULL,
    points     INTEGER NOT NULL,
    bonds      INTEGER NOT NULL,
    art        TEXT NOT NULL,
    share_id   TEXT NOT NULL UNIQUE,
    created_at INTEGER NOT NULL,
    UNIQUE (user_id, puzzle_key)
  );
CREATE INDEX IF NOT EXISTS solves_user ON solves(user_id);
CREATE INDEX IF NOT EXISTS solves_key ON solves(puzzle_key);
CREATE TABLE IF NOT EXISTS progress (
    user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    puzzle_key TEXT NOT NULL,
    art        TEXT NOT NULL,
    updated_at INTEGER NOT NULL,
    PRIMARY KEY (user_id, puzzle_key)
  );
CREATE TABLE IF NOT EXISTS attempts (
    ip    TEXT PRIMARY KEY,
    n     INTEGER NOT NULL,
    until INTEGER NOT NULL
  );
