-- GENERATED by scripts/emit-schema.ts from server/store.ts — do not edit.
-- Regenerate with: bun run db:schema

-- Drops the browser/pairing/attestation era: the device-code tables, the
-- human-vouched harness, and the attested event count. Destructive and
-- irreversible: take a backup first.
--
--   bunx wrangler d1 export pixe-db --remote --output backup.sql
--   bunx wrangler d1 execute pixe-db --remote --file migrations/0003_api_only.sql

-- Runs that never finished pairing were abandoned onboarding, not participants.
DELETE FROM runs WHERE status = 'pending';

DROP INDEX IF EXISTS runs_operator;
DROP TABLE IF EXISTS pair_codes;
DROP TABLE IF EXISTS operators;

ALTER TABLE runs ADD COLUMN model TEXT;
ALTER TABLE runs ADD COLUMN provider TEXT;
UPDATE runs SET model = COALESCE(harness, 'unknown') WHERE model IS NULL;
UPDATE runs SET provider = 'undeclared' WHERE provider IS NULL;
ALTER TABLE runs DROP COLUMN harness;
ALTER TABLE runs DROP COLUMN operator_id;

-- Attested input events no longer exist, so neither does the column.
ALTER TABLE run_solves DROP COLUMN events;

-- The current schema verbatim, so a database that never ran 0001 ends up
-- with the same tables as one that did.

CREATE TABLE IF NOT EXISTS runs (
    id          TEXT PRIMARY KEY,
    secret      TEXT NOT NULL,
    model       TEXT NOT NULL,
    provider    TEXT NOT NULL,
    config      TEXT,
    dialect     TEXT NOT NULL,
    created_at  INTEGER NOT NULL,
    last_at     INTEGER NOT NULL,
    status      TEXT NOT NULL
  );
CREATE INDEX IF NOT EXISTS runs_created ON runs(created_at);
CREATE INDEX IF NOT EXISTS runs_model ON runs(model, provider);
CREATE TABLE IF NOT EXISTS issues (
    run_id     TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
    idx        INTEGER NOT NULL,
    puzzle_key TEXT NOT NULL,
    issued_at  INTEGER NOT NULL,
    closed_at  INTEGER,
    outcome    TEXT,
    api_calls  INTEGER NOT NULL DEFAULT 0,
    probes     INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (run_id, idx)
  );
CREATE UNIQUE INDEX IF NOT EXISTS issues_one_open
     ON issues(run_id) WHERE closed_at IS NULL;
CREATE TABLE IF NOT EXISTS run_solves (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    run_id     TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
    idx        INTEGER NOT NULL,
    puzzle_key TEXT NOT NULL,
    points     INTEGER NOT NULL,
    bonds      INTEGER NOT NULL,
    difficulty INTEGER NOT NULL,
    wall_ms    INTEGER NOT NULL,
    api_calls  INTEGER NOT NULL,
    probes     INTEGER NOT NULL,
    tokens_in  INTEGER,
    tokens_out INTEGER,
    cost_micro INTEGER,
    art        TEXT NOT NULL,
    share_id   TEXT NOT NULL UNIQUE,
    created_at INTEGER NOT NULL,
    UNIQUE (run_id, idx)
  );
CREATE INDEX IF NOT EXISTS run_solves_run ON run_solves(run_id);
CREATE INDEX IF NOT EXISTS run_solves_created ON run_solves(created_at);
CREATE TABLE IF NOT EXISTS attempts (
    ip    TEXT PRIMARY KEY,
    n     INTEGER NOT NULL,
    until INTEGER NOT NULL
  );
