-- GENERATED by scripts/emit-schema.ts from server/store.ts — do not edit.
-- Regenerate with: bun run db:schema

-- Multi-phase rungs: one issue, several boards, one clock. Additive, and
-- safe to run against a live database — every existing row is already
-- correct under the defaults.
--
--   bunx wrangler d1 execute pixe-db --remote --file migrations/0004_multi_phase.sql

ALTER TABLE issues ADD COLUMN phase INTEGER NOT NULL DEFAULT 1;
ALTER TABLE issues ADD COLUMN phase_grids TEXT;

-- The current schema verbatim, so a fresh database ends up identical to a
-- migrated one.

CREATE TABLE IF NOT EXISTS runs (
    id          TEXT PRIMARY KEY,
    secret      TEXT NOT NULL,
    model       TEXT NOT NULL,
    provider    TEXT NOT NULL,
    config      TEXT,
    dialect     TEXT NOT NULL,
    created_at  INTEGER NOT NULL,
    last_at     INTEGER NOT NULL,
    status      TEXT NOT NULL,
    -- 1 iff registration carried the maintainer's key in
    -- X-Pixe-Verified-Key, checked in constant time against PIXE_VERIFIED_KEY.
    -- A vouch about where the run was started, not about the model claim's
    -- truth. Defaults to 0, and a deployment with no key configured can never
    -- write anything else here.
    verified    INTEGER NOT NULL DEFAULT 0
  );
CREATE INDEX IF NOT EXISTS runs_created ON runs(created_at);
CREATE INDEX IF NOT EXISTS runs_model ON runs(model, provider);
CREATE TABLE IF NOT EXISTS issues (
    run_id     TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
    idx        INTEGER NOT NULL,
    puzzle_key TEXT NOT NULL,
    issued_at  INTEGER NOT NULL,
    closed_at  INTEGER,
    outcome    TEXT,
    api_calls  INTEGER NOT NULL DEFAULT 0,
    probes     INTEGER NOT NULL DEFAULT 0,
    -- A rung deep in the ladder is a chain of boards, not one board. phase is
    -- which link is currently open and phase_grids is the JSON array of grids
    -- already accepted for it. The second column is not a log: phase k+1's laws
    -- are derived from those grids, so re-validating the rung from the seed
    -- needs exactly the inputs the derivation originally had.
    phase       INTEGER NOT NULL DEFAULT 1,
    phase_grids TEXT,
    PRIMARY KEY (run_id, idx)
  );
CREATE UNIQUE INDEX IF NOT EXISTS issues_one_open
     ON issues(run_id) WHERE closed_at IS NULL;
CREATE TABLE IF NOT EXISTS run_solves (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    run_id     TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
    idx        INTEGER NOT NULL,
    puzzle_key TEXT NOT NULL,
    points     INTEGER NOT NULL,
    bonds      INTEGER NOT NULL,
    difficulty INTEGER NOT NULL,
    wall_ms    INTEGER NOT NULL,
    api_calls  INTEGER NOT NULL,
    probes     INTEGER NOT NULL,
    tokens_in  INTEGER,
    tokens_out INTEGER,
    cost_micro INTEGER,
    art        TEXT NOT NULL,
    share_id   TEXT NOT NULL UNIQUE,
    created_at INTEGER NOT NULL,
    UNIQUE (run_id, idx)
  );
CREATE INDEX IF NOT EXISTS run_solves_run ON run_solves(run_id);
CREATE INDEX IF NOT EXISTS run_solves_created ON run_solves(created_at);
CREATE TABLE IF NOT EXISTS attempts (
    ip    TEXT PRIMARY KEY,
    n     INTEGER NOT NULL,
    until INTEGER NOT NULL
  );
