/**
 * Writes every migration from the schema in `server/store.ts`.
 *
 * D1 has no equivalent of the `CREATE TABLE IF NOT EXISTS` block the Bun server
 * runs at boot — its schema is applied out-of-band by wrangler, so on D1 these
 * files *are* the schema. Rather than keep a hand-written copy of the DDL that
 * silently drifts from the one the local database uses, all of them are
 * generated from the same constant.
 *
 *   bun run db:schema     # regenerate after changing SCHEMA
 *
 * The migrations past 0001 are generated for a reason that cost real money to
 * learn. 0002 was hand-written when the human game became a benchmark, and then
 * four tables and two columns were added to SCHEMA over the following days
 * without anyone touching it. It rotted into a file that dropped four tables
 * irreversibly and then built a schema the server could not issue a single
 * normal query against. Generating them is what makes that class of mistake
 * impossible rather than merely unlikely.
 */
import { SCHEMA } from "../server/store";

const url = (rel: string) => new URL(`../migrations/${rel}`, import.meta.url).pathname;

const HEADER = [
  "-- GENERATED by scripts/emit-schema.ts from server/store.ts — do not edit.",
  "-- Regenerate with: bun run db:schema",
  "",
];

const body = SCHEMA.map((s) => `${s.trim()};`);

await Bun.write(url("0001_init.sql"), [...HEADER, ...body, ""].join("\n"));

/**
 * The tables the human game used. Dropped rather than migrated: a benchmark row
 * records model, wall clock and probe counts, none of which was ever collected
 * for a human player, so there is nothing to convert and inventing it would be
 * worse than starting clean.
 */
const LEGACY = ["progress", "solves", "sessions", "users"];

await Bun.write(
  url("0002_agent_benchmark.sql"),
  [
    ...HEADER,
    "-- Moves an existing deployment from the human puzzle game to the agent",
    "-- benchmark. Destructive and irreversible: take a backup first.",
    "--",
    "--   bunx wrangler d1 export pixe-db --remote --output backup.sql",
    "--   bunx wrangler d1 execute pixe-db --remote --file migrations/0002_agent_benchmark.sql",
    "",
    ...LEGACY.map((t) => `DROP TABLE IF EXISTS ${t};`),
    "",
    "-- Everything below is the current schema verbatim, so this file cannot",
    "-- drift from what the server actually queries.",
    "",
    ...body,
    "",
  ].join("\n"),
);

/**
 * 0003 is the browser-to-API migration.
 *
 * pixe stopped being a browser benchmark: the device-code pairing flow, the
 * input-event attestation and the execution binding are all gone, and with them
 * the two tables and three columns that only existed to serve them. What
 * replaces the human-vouched `harness` is a self-declared `model` + `provider`
 * pair — unverified, and the schema comment says so.
 *
 * Order matters here and SQLite will tell you so at the worst moment:
 *
 *  - `runs_operator` indexes `operator_id`, and SQLite refuses to drop a column
 *    an index depends on. The index goes first.
 *  - `harness` is copied into `model` before it is dropped, so an existing
 *    deployment keeps its labels instead of ending up with a table of empty
 *    strings. `provider` cannot be recovered from anything and is backfilled
 *    with a marker that reads as what it is.
 *  - `model` and `provider` are added as plain nullable columns. SQLite cannot
 *    add a NOT NULL column without a default, and a default on an identity
 *    column would be a lie waiting to be printed. Fresh databases get the NOT
 *    NULL from 0001; a migrated one carries slightly weaker constraints, which
 *    is the honest trade.
 *  - `pair_codes` references `runs`, so it is dropped before `operators`.
 */
const MIGRATE = [
  "-- Runs that never finished pairing were abandoned onboarding, not participants.",
  "DELETE FROM runs WHERE status = 'pending';",
  "",
  "DROP INDEX IF EXISTS runs_operator;",
  "DROP TABLE IF EXISTS pair_codes;",
  "DROP TABLE IF EXISTS operators;",
  "",
  "ALTER TABLE runs ADD COLUMN model TEXT;",
  "ALTER TABLE runs ADD COLUMN provider TEXT;",
  "UPDATE runs SET model = COALESCE(harness, 'unknown') WHERE model IS NULL;",
  "UPDATE runs SET provider = 'undeclared' WHERE provider IS NULL;",
  "ALTER TABLE runs DROP COLUMN harness;",
  "ALTER TABLE runs DROP COLUMN operator_id;",
  "",
  "-- Attested input events no longer exist, so neither does the column.",
  "ALTER TABLE run_solves DROP COLUMN events;",
];

await Bun.write(
  url("0003_api_only.sql"),
  [
    ...HEADER,
    "-- Drops the browser/pairing/attestation era: the device-code tables, the",
    "-- human-vouched harness, and the attested event count. Destructive and",
    "-- irreversible: take a backup first.",
    "--",
    "--   bunx wrangler d1 export pixe-db --remote --output backup.sql",
    "--   bunx wrangler d1 execute pixe-db --remote --file migrations/0003_api_only.sql",
    "",
    ...MIGRATE,
    "",
    "-- The current schema verbatim, so a database that never ran 0001 ends up",
    "-- with the same tables as one that did.",
    "",
    ...body,
    "",
  ].join("\n"),
);

/**
 * 0004 is the multi-phase rung.
 *
 * A rung deep in the ladder is a chain of boards rather than one board, and the
 * chain lives on the issue: `phase` is which link is open, `phase_grids` is the
 * JSON array of grids already accepted for it. The second column is the one
 * that matters — phase k+1's laws are *derived from* the agent's accepted grid
 * for phase k, so re-validating a rung from the seed needs exactly the inputs
 * the derivation originally had. Without it a finished rung could never be
 * re-checked, and re-checking is the property the anti-cheat story rests on.
 *
 * Purely additive, and safe against a live database. Both columns carry
 * defaults every existing row is already correct under: an issue that predates
 * this migration is phase 1 with nothing accepted behind it, which is exactly
 * what a single-phase rung looks like for its whole life.
 */
const PHASES = [
  "ALTER TABLE issues ADD COLUMN phase INTEGER NOT NULL DEFAULT 1;",
  "ALTER TABLE issues ADD COLUMN phase_grids TEXT;",
];

await Bun.write(
  url("0004_multi_phase.sql"),
  [
    ...HEADER,
    "-- Multi-phase rungs: one issue, several boards, one clock. Additive, and",
    "-- safe to run against a live database — every existing row is already",
    "-- correct under the defaults.",
    "--",
    "--   bunx wrangler d1 execute pixe-db --remote --file migrations/0004_multi_phase.sql",
    "",
    ...PHASES,
    "",
    "-- The current schema verbatim, so a fresh database ends up identical to a",
    "-- migrated one.",
    "",
    ...body,
    "",
  ].join("\n"),
);

/**
 * 0005 is verified runs.
 *
 * A run registered with the maintainer's own secret in `X-Pixe-Verified-Key`
 * carries a vouch nothing else here can offer: that whoever started it held
 * the deployment's own key, which in practice means the maintainer's own
 * machine. It says nothing about whether the declared model is accurate — see
 * `docs/THREAT-MODEL.md` — only about where the run came from.
 *
 * Purely additive, and safe against a live database for the same reason 0004
 * was: the column defaults to 0, which is exactly what every existing row
 * already is under the honest reading — none of them were ever checked
 * against anything, because this column did not exist yet.
 */
const VERIFIED = ["ALTER TABLE runs ADD COLUMN verified INTEGER NOT NULL DEFAULT 0;"];

await Bun.write(
  url("0005_verified.sql"),
  [
    ...HEADER,
    "-- Verified runs: a run registered with the maintainer's own key in",
    "-- X-Pixe-Verified-Key is marked so. Additive and safe to run against a",
    "-- live database — every existing row is already correct under the default.",
    "--",
    "--   bunx wrangler d1 execute pixe-db --remote --file migrations/0005_verified.sql",
    "",
    ...VERIFIED,
    "",
    "-- The current schema verbatim, so a fresh database ends up identical to a",
    "-- migrated one.",
    "",
    ...body,
    "",
  ].join("\n"),
);

console.log(`wrote ${SCHEMA.length} statements to 0001, 0002, 0003, 0004 and 0005`);
