/**
 * Writes `migrations/0001_init.sql` from the schema in `server/store.ts`.
 *
 * D1 has no equivalent of the `CREATE TABLE IF NOT EXISTS` block the Bun
 * server runs at boot — its schema is applied out-of-band by wrangler. Rather
 * than keep a hand-written copy of the DDL that silently drifts from the one
 * the local database uses, the migration is generated from the same constant.
 *
 *   bun run db:schema     # regenerate after changing SCHEMA
 */
import { SCHEMA } from "../server/store";

const OUT = new URL("../migrations/0001_init.sql", import.meta.url).pathname;

const sql = [
  "-- GENERATED by scripts/emit-schema.ts from server/store.ts — do not edit.",
  "-- Regenerate with: bun run db:schema",
  "",
  ...SCHEMA.map((s) => `${s.trim()};`),
  "",
].join("\n");

await Bun.write(OUT, sql);
console.log(`wrote ${SCHEMA.length} statements to migrations/0001_init.sql`);
