/**
 * Writes both migrations from the schema in `server/store.ts`.
 *
 * D1 has no equivalent of the `CREATE TABLE IF NOT EXISTS` block the Bun server
 * runs at boot — its schema is applied out-of-band by wrangler, so on D1 these
 * files *are* the schema. Rather than keep a hand-written copy of the DDL that
 * silently drifts from the one the local database uses, both are generated from
 * the same constant.
 *
 *   bun run db:schema     # regenerate after changing SCHEMA
 *
 * 0002 is generated for a reason that cost real money to learn. It was
 * hand-written when the human game became a benchmark, and then `operators`,
 * `pair_codes`, `runs.operator_id` and both `probes` columns were added to
 * SCHEMA over the following days without anyone touching it. It rotted into a
 * file that dropped four tables irreversibly and then built a schema the server
 * could not issue a single normal query against — registration, pairing and
 * every solve write would have failed at the first request, with the DROPs
 * already committed. Generating it is what makes that class of mistake
 * impossible rather than merely unlikely.
 */
import { SCHEMA } from "../server/store";

const url = (rel: string) => new URL(`../migrations/${rel}`, import.meta.url).pathname;

const HEADER = [
  "-- GENERATED by scripts/emit-schema.ts from server/store.ts — do not edit.",
  "-- Regenerate with: bun run db:schema",
  "",
];

const body = SCHEMA.map((s) => `${s.trim()};`);

await Bun.write(url("0001_init.sql"), [...HEADER, ...body, ""].join("\n"));

/**
 * The tables the human game used. Dropped rather than migrated: a benchmark row
 * records harness, wall clock and probe counts, none of which was ever
 * collected for a human player, so there is nothing to convert and inventing it
 * would be worse than starting clean.
 */
const LEGACY = ["progress", "solves", "sessions", "users"];

await Bun.write(
  url("0002_agent_benchmark.sql"),
  [
    ...HEADER,
    "-- Moves an existing deployment from the human puzzle game to the agent",
    "-- benchmark. Destructive and irreversible: take a backup first.",
    "--",
    "--   bunx wrangler d1 export pixe-db --remote --output backup.sql",
    "--   bunx wrangler d1 execute pixe-db --remote --file migrations/0002_agent_benchmark.sql",
    "",
    ...LEGACY.map((t) => `DROP TABLE IF EXISTS ${t};`),
    "",
    "-- Everything below is the current schema verbatim, so this file cannot",
    "-- drift from what the server actually queries.",
    "",
    ...body,
    "",
  ].join("\n"),
);

console.log(`wrote ${SCHEMA.length} statements to 0001_init.sql and 0002_agent_benchmark.sql`);
